import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import supabase from '@/supabase';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function SignUp() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  async function handleSubmit(e) {
    e.preventDefault();
    let { data, error } = await supabase.auth.signUp({
      email,
      password,
    });
    alert('Check your email to confirm your account');
  }

  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h2>Sign up</h2>
        <form onSubmit={handleSubmit}>
          <label>
            Email:
            <input
              type='email'
              value={email}
              onChange={(event) => setEmail(event.target.value)}
            />
          </label>
          <br />
          <label>
            Password:
            <input
              type='password'
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
          </label>
          <br />
          <input type='submit' value='Submit' />
        </form>

        <div>
          <p>
            Already have an account? <Link href='/sign-in'>Sign in</Link>
          </p>
        </div>
      </div>
    </>
  );
}
