import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import supabase from '@/supabase';
import Link from 'next/link';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] });

export default function SignIn() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const router = useRouter();

  async function handleSubmit(e) {
    e.preventDefault();
    let { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    router.push('/welcome/about');
  }

  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Blind Saturday</h1>
          <div>
            <h2>Sign in</h2>
            <form onSubmit={handleSubmit}>
              <label>
                Email:
                <input
                  type='email'
                  value={email}
                  onChange={(event) => setEmail(event.target.value)}
                />
              </label>
              <br />
              <label>
                Password:
                <input
                  type='password'
                  value={password}
                  onChange={(event) => setPassword(event.target.value)}
                />
              </label>
              <br />
              <input type='submit' value='Submit' />
            </form>

            <div>
              <p>
                Don&apos;t have an account? <Link href='/'>Sign up</Link>
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
