import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import supabase from '@/supabase';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function SignUp() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  async function handleSubmit(e) {
    e.preventDefault();
    let { data, error } = await supabase.auth.signUp({
      email,
      password,
    });
    alert('Check your email to confirm your account');
  }

  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mt-8'>
        <h2 className='text-2xl'>Sign up</h2>
        <form className='mt-4 flex flex-col justify-center'>
          <input
            className='border-4 border-slate-200 w-64 rounded-sm px-6 py-2 outline-none focus:border-slate-300'
            type='email'
            value={email}
            placeholder='Email'
            onChange={(event) => setEmail(event.target.value)}
          />
          <input
            className='mt-2 border-4 border-slate-200 w-64 rounded-sm px-6 py-2 outline-none focus:border-slate-300'
            type='password'
            value={password}
            placeholder='Password'
            onChange={(event) => setPassword(event.target.value)}
          />
        </form>
        <button
          onClick={handleSubmit}
          className='mt-4  text-slate-100 bg-slate-700 px-12 py-4 rounded-md'
        >
          Sign up
        </button>

        <p className='mt-12'>
          Already have an account? <Link href='/sign-in'>Sign in</Link>
        </p>
      </div>
    </>
  );
}
